services:

  postgres:
    container_name: postgres
    image: ankane/pgvector:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./Database/init_db.sql:/docker-entrypoint-initdb.d/1-init_db.sql
      - ./Database/seed.sql:/docker-entrypoint-initdb.d/2-seed.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "pgadmin@pgadmin.com"
      PGADMIN_DEFAULT_PASSWORD: "pgadmin"
    networks:
      - app-network

  embedding_service:
    container_name: embedding_service
    build:
      context: ./Backend/embedding_service
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    networks:
      - app-network
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - ChromaDB

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    depends_on: [otel-collector]
    networks:
      - app-network
  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector-contrib:0.111.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./ChromaDB/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    networks:
      - app-network
      
  ChromaDB:
    container_name: ChromaDB
    image: ghcr.io/chroma-core/chroma
    volumes:
      - chroma_data:/chroma/chroma
    ports:
      - "8000:8000"
    networks:
      - app-network
    environment:
      - CHROMA_SERVER_CORS_ALLOW_ORIGINS=["*"]
      - CHROMA_PERSIST_DIRECTORY=/chroma/chroma
    depends_on:
      - otel-collector
      - zipkin

  rag_service:
    container_name: rag_service
    build:
      context: ./Backend/rag_service
      dockerfile: Dockerfile
    volumes:
      - ./Backend/rag_service:/app
      - ./Database/Query:/app/query
      - /app/node_modules
    ports:
      - "3002:3002"
    networks:
      - app-network
    environment:
      - NODE_ENV=development
      - PORT=3002
      - CHROMA_URL=http://ChromaDB:8000
      - EMBEDDING_SERVICE_URL=http://embedding_service:8001
    depends_on:
      - ChromaDB
      - embedding_service

  chatbot_agent:
    container_name: chatbot_agent
    build:
      context: ./Backend/chatbot_agent
      dockerfile: Dockerfile
    volumes:
      - ./Backend/chatbot_agent:/app
      - /app/node_modules
    ports:
      - "3001:3001"
    networks:
      - app-network
    environment:
      - NODE_ENV=development
      - PORT=3001
      - LM_STUDIO_URL=https://f201-2a01-cb15-4c5-c200-ff2e-b498-e114-f0c2.ngrok-free.app/v1
      - RAG_SERVICE_URL=http://rag_service:3002
    depends_on:
      - rag_service

networks:
  app-network:
    driver: bridge

volumes:
  chroma_data:
  postgres_data:

      
